<?php
/**
 * AttachmentDisplayBody
 *
 * PHP version 5
 *
 * @category Class
 * @package  nirmalsunny\KlarnaPayments
 * @author   Nirmal Sunny and contributors
 * @link     https://github.com/nirmalsunny/klarna-payments
 */

/**
 * Klarna Payments API V1
 *
 * The payments API is used to create a session to offer Klarna's payment methods as part of your checkout.  As soon as the purchase is completed the order should be read and handled using the [`Order Management API`](/order-management/api/).
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.32
 */

namespace nirmalsunny\KlarnaPayments\Model;

use \ArrayAccess;
use \nirmalsunny\KlarnaPayments\ObjectSerializer;

/**
 * AttachmentDisplayBody Class Doc Comment
 *
 * @category Class
 * @description The content of the extra merchant data should be presented as a string inside this property. The body should be an object containing any of the keys and sub-objects described below serialized to JSON. More information on that object can be found [here](https://developers.klarna.com/api/#attachment-schema).
 * @package  nirmalsunny\KlarnaPayments
 * @author   Nirmal Sunny and contributors
 * @link     https://github.com/nirmalsunny/klarna-payments
 */
class AttachmentDisplayBody implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'attachment_display_body';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'air_reservation_details' => '\nirmalsunny\KlarnaPayments\Model\AttachmentDisplayBodyAirReservationDetails[]',
'bus_reservation_details' => '\nirmalsunny\KlarnaPayments\Model\AttachmentDisplayBodyBusReservationDetails[]',
'train_reservation_details' => '\nirmalsunny\KlarnaPayments\Model\AttachmentDisplayBodyBusReservationDetails[]',
'ferry_reservation_details' => '\nirmalsunny\KlarnaPayments\Model\AttachmentDisplayBodyBusReservationDetails[]',
'hotel_reservation_details' => '\nirmalsunny\KlarnaPayments\Model\AttachmentDisplayBodyHotelReservationDetails[]',
'car_rental_reservation_details' => '\nirmalsunny\KlarnaPayments\Model\AttachmentDisplayBodyCarRentalReservationDetails[]',
'event' => '\nirmalsunny\KlarnaPayments\Model\AttachmentDisplayBodyEvent[]',
'voucher' => '\nirmalsunny\KlarnaPayments\Model\AttachmentDisplayBodyVoucher[]',
'subscription' => '\nirmalsunny\KlarnaPayments\Model\AttachmentDisplayBodySubscription[]',
'marketplace_seller_info' => '\nirmalsunny\KlarnaPayments\Model\AttachmentDisplayBodyMarketplaceSellerInfo[]',
'marketplace_winner_info' => '\nirmalsunny\KlarnaPayments\Model\AttachmentDisplayBodyMarketplaceWinnerInfo[]',
'customer_account_info' => '\nirmalsunny\KlarnaPayments\Model\AttachmentDisplayBodyCustomerAccountInfo[]',
'payment_history_full' => '\nirmalsunny\KlarnaPayments\Model\AttachmentDisplayBodyPaymentHistoryFull[]',
'payment_history_simple' => '\nirmalsunny\KlarnaPayments\Model\AttachmentDisplayBodyPaymentHistorySimple[]',
'other_delivery_address' => '\nirmalsunny\KlarnaPayments\Model\AttachmentDisplayBodyOtherDeliveryAddress[]'    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'air_reservation_details' => null,
'bus_reservation_details' => null,
'train_reservation_details' => null,
'ferry_reservation_details' => null,
'hotel_reservation_details' => null,
'car_rental_reservation_details' => null,
'event' => null,
'voucher' => null,
'subscription' => null,
'marketplace_seller_info' => null,
'marketplace_winner_info' => null,
'customer_account_info' => null,
'payment_history_full' => null,
'payment_history_simple' => null,
'other_delivery_address' => null    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'air_reservation_details' => 'air_reservation_details',
'bus_reservation_details' => 'bus_reservation_details',
'train_reservation_details' => 'train_reservation_details',
'ferry_reservation_details' => 'ferry_reservation_details',
'hotel_reservation_details' => 'hotel_reservation_details',
'car_rental_reservation_details' => 'car_rental_reservation_details',
'event' => 'event',
'voucher' => 'voucher',
'subscription' => 'subscription',
'marketplace_seller_info' => 'marketplace_seller_info',
'marketplace_winner_info' => 'marketplace_winner_info',
'customer_account_info' => 'customer_account_info',
'payment_history_full' => 'payment_history_full',
'payment_history_simple' => 'payment_history_simple',
'other_delivery_address' => 'other_delivery_address'    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'air_reservation_details' => 'setAirReservationDetails',
'bus_reservation_details' => 'setBusReservationDetails',
'train_reservation_details' => 'setTrainReservationDetails',
'ferry_reservation_details' => 'setFerryReservationDetails',
'hotel_reservation_details' => 'setHotelReservationDetails',
'car_rental_reservation_details' => 'setCarRentalReservationDetails',
'event' => 'setEvent',
'voucher' => 'setVoucher',
'subscription' => 'setSubscription',
'marketplace_seller_info' => 'setMarketplaceSellerInfo',
'marketplace_winner_info' => 'setMarketplaceWinnerInfo',
'customer_account_info' => 'setCustomerAccountInfo',
'payment_history_full' => 'setPaymentHistoryFull',
'payment_history_simple' => 'setPaymentHistorySimple',
'other_delivery_address' => 'setOtherDeliveryAddress'    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'air_reservation_details' => 'getAirReservationDetails',
'bus_reservation_details' => 'getBusReservationDetails',
'train_reservation_details' => 'getTrainReservationDetails',
'ferry_reservation_details' => 'getFerryReservationDetails',
'hotel_reservation_details' => 'getHotelReservationDetails',
'car_rental_reservation_details' => 'getCarRentalReservationDetails',
'event' => 'getEvent',
'voucher' => 'getVoucher',
'subscription' => 'getSubscription',
'marketplace_seller_info' => 'getMarketplaceSellerInfo',
'marketplace_winner_info' => 'getMarketplaceWinnerInfo',
'customer_account_info' => 'getCustomerAccountInfo',
'payment_history_full' => 'getPaymentHistoryFull',
'payment_history_simple' => 'getPaymentHistorySimple',
'other_delivery_address' => 'getOtherDeliveryAddress'    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['air_reservation_details'] = isset($data['air_reservation_details']) ? $data['air_reservation_details'] : null;
        $this->container['bus_reservation_details'] = isset($data['bus_reservation_details']) ? $data['bus_reservation_details'] : null;
        $this->container['train_reservation_details'] = isset($data['train_reservation_details']) ? $data['train_reservation_details'] : null;
        $this->container['ferry_reservation_details'] = isset($data['ferry_reservation_details']) ? $data['ferry_reservation_details'] : null;
        $this->container['hotel_reservation_details'] = isset($data['hotel_reservation_details']) ? $data['hotel_reservation_details'] : null;
        $this->container['car_rental_reservation_details'] = isset($data['car_rental_reservation_details']) ? $data['car_rental_reservation_details'] : null;
        $this->container['event'] = isset($data['event']) ? $data['event'] : null;
        $this->container['voucher'] = isset($data['voucher']) ? $data['voucher'] : null;
        $this->container['subscription'] = isset($data['subscription']) ? $data['subscription'] : null;
        $this->container['marketplace_seller_info'] = isset($data['marketplace_seller_info']) ? $data['marketplace_seller_info'] : null;
        $this->container['marketplace_winner_info'] = isset($data['marketplace_winner_info']) ? $data['marketplace_winner_info'] : null;
        $this->container['customer_account_info'] = isset($data['customer_account_info']) ? $data['customer_account_info'] : null;
        $this->container['payment_history_full'] = isset($data['payment_history_full']) ? $data['payment_history_full'] : null;
        $this->container['payment_history_simple'] = isset($data['payment_history_simple']) ? $data['payment_history_simple'] : null;
        $this->container['other_delivery_address'] = isset($data['other_delivery_address']) ? $data['other_delivery_address'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets air_reservation_details
     *
     * @return \nirmalsunny\KlarnaPayments\Model\AttachmentDisplayBodyAirReservationDetails[]
     */
    public function getAirReservationDetails()
    {
        return $this->container['air_reservation_details'];
    }

    /**
     * Sets air_reservation_details
     *
     * @param \nirmalsunny\KlarnaPayments\Model\AttachmentDisplayBodyAirReservationDetails[] $air_reservation_details Details about the reservation of airline tickets
     *
     * @return $this
     */
    public function setAirReservationDetails($air_reservation_details)
    {
        $this->container['air_reservation_details'] = $air_reservation_details;

        return $this;
    }

    /**
     * Gets bus_reservation_details
     *
     * @return \nirmalsunny\KlarnaPayments\Model\AttachmentDisplayBodyBusReservationDetails[]
     */
    public function getBusReservationDetails()
    {
        return $this->container['bus_reservation_details'];
    }

    /**
     * Sets bus_reservation_details
     *
     * @param \nirmalsunny\KlarnaPayments\Model\AttachmentDisplayBodyBusReservationDetails[] $bus_reservation_details Details about the reservation of bus tickets
     *
     * @return $this
     */
    public function setBusReservationDetails($bus_reservation_details)
    {
        $this->container['bus_reservation_details'] = $bus_reservation_details;

        return $this;
    }

    /**
     * Gets train_reservation_details
     *
     * @return \nirmalsunny\KlarnaPayments\Model\AttachmentDisplayBodyBusReservationDetails[]
     */
    public function getTrainReservationDetails()
    {
        return $this->container['train_reservation_details'];
    }

    /**
     * Sets train_reservation_details
     *
     * @param \nirmalsunny\KlarnaPayments\Model\AttachmentDisplayBodyBusReservationDetails[] $train_reservation_details Details about the reservation of train tickets
     *
     * @return $this
     */
    public function setTrainReservationDetails($train_reservation_details)
    {
        $this->container['train_reservation_details'] = $train_reservation_details;

        return $this;
    }

    /**
     * Gets ferry_reservation_details
     *
     * @return \nirmalsunny\KlarnaPayments\Model\AttachmentDisplayBodyBusReservationDetails[]
     */
    public function getFerryReservationDetails()
    {
        return $this->container['ferry_reservation_details'];
    }

    /**
     * Sets ferry_reservation_details
     *
     * @param \nirmalsunny\KlarnaPayments\Model\AttachmentDisplayBodyBusReservationDetails[] $ferry_reservation_details Details about the reservation of ferry tickets
     *
     * @return $this
     */
    public function setFerryReservationDetails($ferry_reservation_details)
    {
        $this->container['ferry_reservation_details'] = $ferry_reservation_details;

        return $this;
    }

    /**
     * Gets hotel_reservation_details
     *
     * @return \nirmalsunny\KlarnaPayments\Model\AttachmentDisplayBodyHotelReservationDetails[]
     */
    public function getHotelReservationDetails()
    {
        return $this->container['hotel_reservation_details'];
    }

    /**
     * Sets hotel_reservation_details
     *
     * @param \nirmalsunny\KlarnaPayments\Model\AttachmentDisplayBodyHotelReservationDetails[] $hotel_reservation_details Details about the reservation of hotel rooms
     *
     * @return $this
     */
    public function setHotelReservationDetails($hotel_reservation_details)
    {
        $this->container['hotel_reservation_details'] = $hotel_reservation_details;

        return $this;
    }

    /**
     * Gets car_rental_reservation_details
     *
     * @return \nirmalsunny\KlarnaPayments\Model\AttachmentDisplayBodyCarRentalReservationDetails[]
     */
    public function getCarRentalReservationDetails()
    {
        return $this->container['car_rental_reservation_details'];
    }

    /**
     * Sets car_rental_reservation_details
     *
     * @param \nirmalsunny\KlarnaPayments\Model\AttachmentDisplayBodyCarRentalReservationDetails[] $car_rental_reservation_details Details about the reservation of rental cars
     *
     * @return $this
     */
    public function setCarRentalReservationDetails($car_rental_reservation_details)
    {
        $this->container['car_rental_reservation_details'] = $car_rental_reservation_details;

        return $this;
    }

    /**
     * Gets event
     *
     * @return \nirmalsunny\KlarnaPayments\Model\AttachmentDisplayBodyEvent[]
     */
    public function getEvent()
    {
        return $this->container['event'];
    }

    /**
     * Sets event
     *
     * @param \nirmalsunny\KlarnaPayments\Model\AttachmentDisplayBodyEvent[] $event event
     *
     * @return $this
     */
    public function setEvent($event)
    {
        $this->container['event'] = $event;

        return $this;
    }

    /**
     * Gets voucher
     *
     * @return \nirmalsunny\KlarnaPayments\Model\AttachmentDisplayBodyVoucher[]
     */
    public function getVoucher()
    {
        return $this->container['voucher'];
    }

    /**
     * Sets voucher
     *
     * @param \nirmalsunny\KlarnaPayments\Model\AttachmentDisplayBodyVoucher[] $voucher voucher
     *
     * @return $this
     */
    public function setVoucher($voucher)
    {
        $this->container['voucher'] = $voucher;

        return $this;
    }

    /**
     * Gets subscription
     *
     * @return \nirmalsunny\KlarnaPayments\Model\AttachmentDisplayBodySubscription[]
     */
    public function getSubscription()
    {
        return $this->container['subscription'];
    }

    /**
     * Sets subscription
     *
     * @param \nirmalsunny\KlarnaPayments\Model\AttachmentDisplayBodySubscription[] $subscription subscription
     *
     * @return $this
     */
    public function setSubscription($subscription)
    {
        $this->container['subscription'] = $subscription;

        return $this;
    }

    /**
     * Gets marketplace_seller_info
     *
     * @return \nirmalsunny\KlarnaPayments\Model\AttachmentDisplayBodyMarketplaceSellerInfo[]
     */
    public function getMarketplaceSellerInfo()
    {
        return $this->container['marketplace_seller_info'];
    }

    /**
     * Sets marketplace_seller_info
     *
     * @param \nirmalsunny\KlarnaPayments\Model\AttachmentDisplayBodyMarketplaceSellerInfo[] $marketplace_seller_info marketplace_seller_info
     *
     * @return $this
     */
    public function setMarketplaceSellerInfo($marketplace_seller_info)
    {
        $this->container['marketplace_seller_info'] = $marketplace_seller_info;

        return $this;
    }

    /**
     * Gets marketplace_winner_info
     *
     * @return \nirmalsunny\KlarnaPayments\Model\AttachmentDisplayBodyMarketplaceWinnerInfo[]
     */
    public function getMarketplaceWinnerInfo()
    {
        return $this->container['marketplace_winner_info'];
    }

    /**
     * Sets marketplace_winner_info
     *
     * @param \nirmalsunny\KlarnaPayments\Model\AttachmentDisplayBodyMarketplaceWinnerInfo[] $marketplace_winner_info marketplace_winner_info
     *
     * @return $this
     */
    public function setMarketplaceWinnerInfo($marketplace_winner_info)
    {
        $this->container['marketplace_winner_info'] = $marketplace_winner_info;

        return $this;
    }

    /**
     * Gets customer_account_info
     *
     * @return \nirmalsunny\KlarnaPayments\Model\AttachmentDisplayBodyCustomerAccountInfo[]
     */
    public function getCustomerAccountInfo()
    {
        return $this->container['customer_account_info'];
    }

    /**
     * Sets customer_account_info
     *
     * @param \nirmalsunny\KlarnaPayments\Model\AttachmentDisplayBodyCustomerAccountInfo[] $customer_account_info customer_account_info
     *
     * @return $this
     */
    public function setCustomerAccountInfo($customer_account_info)
    {
        $this->container['customer_account_info'] = $customer_account_info;

        return $this;
    }

    /**
     * Gets payment_history_full
     *
     * @return \nirmalsunny\KlarnaPayments\Model\AttachmentDisplayBodyPaymentHistoryFull[]
     */
    public function getPaymentHistoryFull()
    {
        return $this->container['payment_history_full'];
    }

    /**
     * Sets payment_history_full
     *
     * @param \nirmalsunny\KlarnaPayments\Model\AttachmentDisplayBodyPaymentHistoryFull[] $payment_history_full payment_history_full
     *
     * @return $this
     */
    public function setPaymentHistoryFull($payment_history_full)
    {
        $this->container['payment_history_full'] = $payment_history_full;

        return $this;
    }

    /**
     * Gets payment_history_simple
     *
     * @return \nirmalsunny\KlarnaPayments\Model\AttachmentDisplayBodyPaymentHistorySimple[]
     */
    public function getPaymentHistorySimple()
    {
        return $this->container['payment_history_simple'];
    }

    /**
     * Sets payment_history_simple
     *
     * @param \nirmalsunny\KlarnaPayments\Model\AttachmentDisplayBodyPaymentHistorySimple[] $payment_history_simple payment_history_simple
     *
     * @return $this
     */
    public function setPaymentHistorySimple($payment_history_simple)
    {
        $this->container['payment_history_simple'] = $payment_history_simple;

        return $this;
    }

    /**
     * Gets other_delivery_address
     *
     * @return \nirmalsunny\KlarnaPayments\Model\AttachmentDisplayBodyOtherDeliveryAddress[]
     */
    public function getOtherDeliveryAddress()
    {
        return $this->container['other_delivery_address'];
    }

    /**
     * Sets other_delivery_address
     *
     * @param \nirmalsunny\KlarnaPayments\Model\AttachmentDisplayBodyOtherDeliveryAddress[] $other_delivery_address other_delivery_address
     *
     * @return $this
     */
    public function setOtherDeliveryAddress($other_delivery_address)
    {
        $this->container['other_delivery_address'] = $other_delivery_address;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
